### ISSUE TITLE
Do you support kali linux

### ISSUE THREAD

**Issue by timflannagan** [nathan-weinberg/bash-scripts#2]

**Comment by nathan-weinberg** [comment]
There are no plans to support Kali linux at this time

**Comment by Daniel-Pivonka** [comment]
thats a shame

**Comment by timflannagan** [comment]
I, unfortunately, will have to un-star this repository as I don't support anyone who neglects to support kali linux.

**Comment by nathan-weinberg** [comment]
Sad to hear! I would welcome a PR that brings on support for Kali linux

**Comment by timflannagan** [comment]
@nathan-weinberg any plans for prioritizing the support of kali linux in the context of your current roadmap? Is that something @Daniel-Pivonka can help you scope out?

**Comment by Daniel-Pivonka** [comment]
Sorry will not have time to do that’s as I’m looking into support for raspbian at the moment

**Comment by timflannagan** [comment]
@Daniel-Pivonka that should be a low priority task, and you should divert your attention into kali Linux. Let's set up a series of meetings to record your progress with the aforementioned task.
